name: start
version: 0.1.0
author: Yehor Lvivski <lvivski@gmail.com>
description: Sinatra inspired Web framework
homepage: http://github.com/lvivski/start
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: any
  unittest: '>=0.2.7'
