name: start
version: 0.0.1
description: Sinatra inspired Web framework
author: Yehor Lvivksi <lvivski@gmail.com>
homepage: http://github.com/lvivski/start
dependencies:
  hart: ">=0.0.2"
  unittest:
    sdk: unittest